// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNf3mAFeiQvebEBd4NxbtsbcwhTZshI0E',
    appId: '1:715766512834:android:4be4fb8365b1d1e53a4f5b',
    messagingSenderId: '715766512834',
    projectId: 'decibel-6de8e',
    storageBucket: 'decibel-6de8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQY830TAdTSfzxHzOut3KhGZiG0DoDfrg',
    appId: '1:715766512834:ios:85fc6c3e8671fc813a4f5b',
    messagingSenderId: '715766512834',
    projectId: 'decibel-6de8e',
    storageBucket: 'decibel-6de8e.firebasestorage.app',
    iosBundleId: 'com.example.projetoCmGrupo13Pl1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNf3mAFeiQvebEBd4NxbtsbcwhTZshI0E',
    appId: '1:715766512834:web:4be4fb8365b1d1e53a4f5b',
    messagingSenderId: '715766512834',
    projectId: 'decibel-6de8e',
    authDomain: 'decibel-6de8e.firebaseapp.com',
    storageBucket: 'decibel-6de8e.firebasestorage.app',
  );
}
